---

pipeline:
  test:
    image: artioml/f5-ansible:su
    commands:
      - /bin/sh test/run.sh
  deploy:
    image: artioml/f5-ansible:su
    commands:
      - ./runsible.py --iac
    when:
      branch: master

...
