---

- name: "Imperative: Deploy / teardown a web app (VS, pool, nodes)"
  hosts: bigips
  gather_facts: False
  connection: local

  vars:
    state: "present"
    service_name: "vs_Web"
    service_ip: "10.100.115.10"

  environment: "{{ bigip_env }}"

  tasks:
    - name: Adjust a VS
      bigip_virtual_server:
        name: "{{ service_name }}"
        destination: "{{ service_ip }}"
        port: "443"
        description: "Web App"
        snat: "Automap"
        all_profiles:
          - "tcp-lan-optimized"
          - "clientssl"
          - "http"
          - "analytics"
        state: "{{ state }}"

    - name: Adjust a pool
      bigip_pool:
        name: "pool_Web"
        monitors: "/Common/http"
        monitor_type: "and_list"
        slow_ramp_time: "120"
        lb_method: "ratio-member"
        state: "{{ state }}"

    - name: Adjust first node
      bigip_node:
        name: "node_Srv1"
        host: "{{ groups['webservers'][0] }}"
        state: "{{ state }}"

    - name: Adjust second node
      bigip_node:
        name: "node_Srv2"
        host: "{{ groups['webservers'][1] }}"
        state: "{{ state }}"

    - name: Add nodes to pool
      bigip_pool_member:
        name: "{{ item.name }}"
        host: "{{ item.host }}"
        port: "80"
        pool: "pool_Web"
        state: "{{ state }}"
      with_items:
        - name: "node_Srv1"
          host: "{{ groups['webservers'][0] }}"
        - name: "node_Srv2"
          host: "{{ groups['webservers'][1] }}"
      when: state == "present"

    - name: Update a VS
      bigip_virtual_server:
        name: "{{ service_name }}"
        pool: "pool_Web"
        state: "{{ state }}"
      when: state == "present"

    - import_tasks: slack.yml
      vars:
        msg: "Web app"

...
