---

- name: Get iApp service list
  uri:
    url: "https://{{ inventory_hostname }}/mgmt/tm/cloud/services/iapp/"
    user: "{{ bigip_user }}"
    password: "{{ bigip_pass }}"
    validate_certs: false
    return_content: true
  register: service_list

...
