---

apps:
  iapp_Web1:
    description: A web app protected by WAF
    ip: 10.100.115.11
    owner: artioml
    state: true
  iapp_Web2:
    description:
    ip: 10.100.115.12
    owner:
    state: false

...
