---

apps:
  iapp_Web1:
    description: A web app protected by WAF
    ip: 10.100.115.11
    group: webservers
    state: true
  iapp_Web2:
    description:
    ip: 10.100.115.12
    group:
    state: false

...
